import type { Metadata } from "next";

import { Noto_Sans } from "next/font/google";
import RecoilRootWrapper from "./RecoilWrapper";
import { ThemeProvider } from "@/components/Provider";

import "./globals.css";

const notoSansKr = Noto_Sans({
  subsets: ["latin"],
  variable: "--noto_sans",
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKr.variable} `}>
        <RecoilRootWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
